name: Flask App CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask selenium

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y google-chrome-stable

    - name: Start Xvfb
      run: |
        Xvfb :99 -ac &
        export DISPLAY=:99

    - name: Start Flask app
      run: |
        nohup python app.py &

    - name: Run tests
      run: |
        python -c "
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options

        options = Options()
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        options.add_argument('--disable-dev-shm-usage')

        driver = webdriver.Chrome(options=options)
        driver.get('http://localhost:5000')
        # ...additional test code...
        driver.quit()
        "

    - name: Run tests2
      run: | 
      python -m unittest discover -s tests -v